version: ~> 1.0
os: linux
dist: bionic
language: node_js
node_js:
  - 14
cache: npm
jobs:
  include:
    - stage: frontend-tests
      name: "Frontend Unit Tests"
      before_script:
        - cd frontend
        - npm install -g @vue/cli
        - npm install
      script: npm run test
    - stage: backend-tests
      name: "Backend Unit Tests"
      before_script:
        - cd backend
        - npm install
      script: npm test
    - stage: build
      name: "Build Docker Images"
      script:
        - cd frontend
        - docker build -t rishabhjaitly/stayio-frontend .
        - cd ../backend
        - docker build -t rishabhjaitly/stayio-backend .
    - if: branch = master
      stage: deploy
      name: "Deploy to DockerHub"
      before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - cd ..
      script:
        - cd frontend
        - docker build -t rishabhjaitly/stayio-frontend .
        - docker push rishabhjaitly/stayio-frontend
        - cd ../backend
        - docker build -t rishabhjaitly/stayio-backend .
        - docker push rishabhjaitly/stayio-backend
