name: Build Workflow
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Frontend Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          cd frontend
          docker build -t $DOCKER_USERNAME/stayio-frontend .
      - name: Build Backend Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          cd backend
          docker build -t $DOCKER_USERNAME/stayio-backend .
      - name: Push Images to Package Registries
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GH_DOCKER_TOKEN: ${{ secrets.GH_DOCKER_TOKEN }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          cd frontend
          docker build -t $DOCKER_USERNAME/stayio-frontend .
          cd ../backend
          docker build -t $DOCKER_USERNAME/stayio-backend .
          cd ..
          docker push $DOCKER_USERNAME/stayio-frontend
          docker push $DOCKER_USERNAME/stayio-backend
          echo "$GH_DOCKER_TOKEN" | docker login docker.pkg.github.com -u $GH_USERNAME --password-stdin
          docker tag $DOCKER_USERNAME/stayio-frontend docker.pkg.github.com/$GH_USERNAME/stay.io/stayio-frontend
          docker tag $DOCKER_USERNAME/stayio-backend docker.pkg.github.com/$GH_USERNAME/stay.io/stayio-backend
          docker push docker.pkg.github.com/$GH_USERNAME/stay.io/stayio-frontend
          docker push docker.pkg.github.com/$GH_USERNAME/stay.io/stayio-backend
